### ISSUE TITLE
Improve frontend UX/UI

### ISSUE THREAD

**Issue by HeinzNepe** [recalstudios/recal-social-client#23]

**Comment by soni801** [comment]
Improving the buttons and overall UX of the frontend

**Comment by soni801** [comment]
Addressed in the following commits:

- df59825574f39f04384f4dd8034e674e6339ad2c
- 0938f41d3dc80d8f7ad5f67701e5cf794491eb01
- f6b9c1046ea4bb5ef41cd32c9f5d0015b57889d1
- de7e7b0bf5f0950e43f5e5a14659ef0d0f99412c
- fcb2fbb6f4dcc6e31473428881246167c4cc59e3
- 20912aa4a23601498c301e183206f5a7bd37326b
- cbfbea78a30ca8b466ad9e6f87fc436afd94bb84
- 48fac9e4ad15e6c8fb9df07b30e7925f5e1a1357
- 174bcabb8104292873f65408973a4015ab355fe6
- 163e9f74c63a8f9d82904d1df768c439ed396988
